version: '3'

services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - sso_server
  #   networks:
  #     - sso
  # sso_server:
  #   image: sso-server
  #   # ports:
  #   #   - 3001:3001
  #   #   - 3002:3002
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env.development
  #   networks:
  #     - sso

  db:
    container_name: sso-msa-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/config/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sso
      time_zone: UTC
    networks:
      - sso
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - sso
volumes:
  db_volume:
networks:
  sso:
    external: true
