version: '3'

services:
  server:
    image: sso-server
    # ports:
    #   - 3001:3001
    #   - 3002:3002
    env_file:
      - .env.production
    networks:
      - sso
      - nginx
  db:
    container_name: sso-db
    image: mysql
    restart: always
    volumes:
      - sso_db_volume:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/config/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sso
      time_zone: UTC
    networks:
      - sso

volumes:
  sso_db_volume:
networks:
  sso:
    external: true
  nginx:
    external: true
